version: "3.9"
services: 


  wordpres_db:
    image: mariadb:10.6.4-focal
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=rootstudent
      - MYSQL_DATABASE=student
      - MYSQL_USER=student
      - MYSQL_PASSWORD=student
    expose:
      - 3306
      - 33060
      
  wordpress:
    image: wordpress:latest
    ports:
      - 80
    restart: always
    environment:
      - WORDPRESS_DB_HOST=wordpress_db
      - WORDPRESS_DB_USER=student
      - WORDPRESS_DB_PASSWORD=student
      - WORDPRESS_DB_NAME=student
    volumes:
      - wp_files:/var/www/html

#nginx configuration
  nginx:
    image: nginx:alpine
    container_name: nginx
    depends_on: 
      - wordpress
    ports:
      - 8085:80
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - wp_files:/var/www/html

#mediawiki configuration
  mediawiki:
    image: mediawiki
    restart: always
    ports:
      - 8080:80
    links:
      - db_mediawiki
    volumes:
      - images:/var/www/html/images

#mediawiki db configuration
  db_mediawiki:
    image: mariadb:10
    restart: always
    environment:
      MYSQL_DATABASE: my_wiki
      MYSQL_USER: wikiuser
      MYSQL_PASSWORD: example
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    volumes:
      - media_db:/var/lib/mysql

#filebrowser configuration
  filebrowser:
    image: hurlenko/filebrowser
    restart: always
    user: "1000:1000"
    ports:
      - 8188:8080
    volumes:
      - /:/data
      - ./config:/config

#portainer configuration
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./portainer-data:/data
    ports:
      - 9000:9000

#volumes
volumes: 
  wp_files:
  images:
  media_db:
  db_data: