version: "3.9"

services: 

  #wordpress db configuration
  wordpress_db:
    image: mariadb:10.6.4-focal
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: ${WP_DB_NAME}
      MYSQL_USER: ${WP_DB_USER}
      MYSQL_PASSWORD: ${WP_DB_PWD}
      MYSQL_ROOT_PASSWORD: ${WP_DB_ROOT_PWD}
    expose:
      - 3306
      - 33060
      
  #wordpress configuration
  wordpress:
    image: wordpress:latest
    ports:
      - 80
    restart: always
    environment:
      WORDPRESS_DB_HOST: ${WP_HOST}
      WORDPRESS_DB_USER: ${WP_NAME}
      WORDPRESS_DB_PASSWORD: ${WP_USER}
      WORDPRESS_DB_NAME: ${WP_PWD}
    volumes:
      - wp_files:/var/www/html

#nginx configuration
  nginx:
    image: nginx:alpine
    container_name: nginx
    depends_on: 
      - wordpress
    ports:
      - ${NGINX_LOCAL}:${NGINX_DOCKER}
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - wp_files:/var/www/html

#mediawiki configuration
  mediawiki:
    image: mediawiki
    restart: always
    ports:
      - ${MW_LOCAL}:${MW_DOCKER}
    links:
      - mediawiki_db
    volumes:
      - images:/var/www/html/images
      - ./LocalSettings.php:/var/www/html/LocalSettings.php

#mediawiki db configuration
  mediawiki_db:
    image: mariadb:10
    restart: always
    environment:
      MYSQL_DATABASE: ${MW_DB_NAME}
      MYSQL_USER: ${MW_DB_USER}
      MYSQL_PASSWORD: ${MW_DB_PWD}
      MYSQL_ROOT_PASSWORD: ${MW_DB_ROOT_PWD}
    volumes:
      - /var/lib/mysql
      - ./db/mediawiki_init.sql:/docker-entrypoint-initdb.d/init.sql

#filebrowser configuration
  filebrowser:
    image: hurlenko/filebrowser
    restart: always
    user: "1000:1000"
    ports:
      - ${FB_LOCAL}:${FB_DOCKER}
    volumes:
      - ./data:/data

#portainer configuration
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./portainer-data:/data
    ports:
      - ${PT_LOCAL}:${PT_DOCKER}

#volumes
volumes: 
  wp_files:
  images:
  db_data: