version: "3.7"
services: 
#Ddatabase wordpress configuration
  db_wordpress:
    image: mariadb:10
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
#wordpress configuration
  wordpress:
    image: wordpress:5-fpm-alpine
    links:
      - db_wordpress 
    volumes:
      - wp_files:/var/www/html
    environment:
      WORDPRESS_DB_HOST: "${WORDPRESS_DB_HOST}"
      WORDPRESS_DB_NAME: "${WORDPRESS_DB_NAME}"
      WORDPRESS_DB_USER: "${WORDPRESS_DB_USER}"
      WORDPRESS_DB_PASSWORD: "${WORDPRESS_DB_PASSWORD}"
#Nginx config
  nginx:
    image: nginx:alpine
    container_name: nginx
    depends_on: 
      - wordpress
    ports:
      - 8085:80
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - wp_files:/var/www/html
#Mediawiki configuration
  mediawiki:
    image: mediawiki
    restart: always
    ports:
      - 8081:80
    links:
      - db_mediawiki
    volumes:
      - images:/var/www/html/images
#Database Mediawiki configuration
  db_mediawiki:
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: my_wiki
      MYSQL_USER: wikiuser
      MYSQL_PASSWORD: example
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    volumes:
      - db:/var/lib/mysql
#Filebrowser
  filebrowser:
     image: filebrowser/filebrowser
     container_name: filebrowser
     volumes:
       - ./.data:/data
     environment:
       - FILEBROWSER_PORT=80
       - FILEBROWSER_BASEURL=http://localhost/
     ports:
       - "8003:80"

     restart: always


volumes: 
  wp_files: 
  images:
  db: